### ISSUE TITLE
Link to blog is broken

### ISSUE THREAD

**Issue by Bodobolero** [SvenBayer/sven-hammerdb-benchmark#2]
It would be nice if you could add a PDF version of your blogpost [https://svenbayer.blog](https://svenbayer.blog/benchmarking-amazon-rds-graviton2/) or correct the link - it doesn't work for me.

**Comment by SvenBayer** [comment]
https://svenbayer.wordpress.com/2021/02/08/benchmarking-amazon-rds-graviton2/
See here. But the benchmark is old and things may have changed.

**Comment by Bodobolero** [comment]
Thank you
